export const GET_CHARACTERS_LIST = "GET_CHARACTERS_LIST";
export const GET_CHARACTERS_LIST_SUCCESS = "GET_CHARACTERS_LIST_SUCCESS";
export const GET_CHARACTERS_LIST_ERROR = "GET_CHARACTERS_LIST_ERROR";
